Rails.application.routes.draw do

  root to: 'luz#splash', as: 'root'

  get '/home', to: 'luz#home'
  get '/aboutme', to: 'luz#aboutme'
  get '/exhibitions', to: 'luz#exhibitions'
  get '/photojournalism', to: 'luz#photojournalism'
  get '/features', to: 'luz#features'
  get '/blog', to: 'luz#blog'

  get '/peace', to: 'photojournal#peaceindex'
  get '/women', to: 'photojournal#womenindex'
  get '/children', to: 'photojournal#childrenindex'
  get '/images', to: 'photojournal#imagesindex'
  get '/para', to: 'photojournal#paraindex'
  get '/urban', to: 'photojournal#urbanindex'
  get '/around', to: 'photojournal#aroundindex'
  get '/jobs', to: 'photojournal#jobsindex'
  get '/cyclists', to: 'photojournal#cyclistsindex'
  get '/pick', to: 'photojournal#pickindex'

  get '/retrospective', to: 'exhibits#retrospective'
  get '/infrarojo', to: 'exhibits#infrarojo'
  get '/lejos', to: 'exhibits#lejos'
  get '/bwb', to: 'exhibits#bwb'
  get '/faces', to: 'exhibits#faces'
  get '/old', to: 'exhibits#old'
  get '/recyclers', to: 'exhibits#recyclers'
  get '/cesar', to: 'exhibits#cesar'

  get '/peace1', to: 'show#peace1'
  get '/peace2', to: 'show#peace2'
  get '/peace3', to: 'show#peace3'
  get '/peace4', to: 'show#peace4'
  get '/peace6', to: 'show#peace6'

  get '/despedida', to: 'show#despedida'
  get '/patrullando', to: 'show#patrullando'
  get '/desalojos', to: 'show#desalojos'
  get '/carlospizarro', to: 'show#carlospizarro'
  get '/sinpalabras', to: 'show#sinpalabras'
  get '/dejaciondearmas', to: 'show#dejaciondearmas'
  get '/cordoba95', to: 'show#cordoba95'
  get '/paras2', to: 'show#paras2'
  get '/elcartucho', to: 'show#elcartucho'
  get '/cartamagna', to: 'show#cartamagna'

  get '/aztecaboy', to: 'show#aztecaboy'
  get '/boysandcows', to: 'show#boysandcows'
  get '/candle', to: 'show#candle'
  get '/comida', to: 'show#comida'
  get '/couple', to: 'show#couple'
  get '/girls', to: 'show#girls'
  get '/familia03', to: 'show#familia03'
  get '/kikayoga', to: 'show#kikayoga'
  get '/kika', to: 'show#kika'
  get '/mariachi', to: 'show#mariachi'
  get '/skull', to: 'show#skull'

  get '/businesswarbusiness', to: 'show#businesswarbusiness'
  get '/err', to: 'show#err'
  get '/estratagia', to: 'show#estratagia'
  get '/negocianes', to: 'show#negocianes'
  get '/negociaciones', to: 'show#negociaciones'


  get '/elcartucho92', to: 'show#elcartucho92'
  get '/laflaca', to: 'show#laflaca'
  get '/lapastora', to: 'show#lapastora'
  get '/elcartucho', to: 'show#elcartucho'

  get '/buga89', to: 'show#buga89'
  get '/buga1', to: 'show#buga1'
  get '/circulo', to: 'show#circulo'
  get '/encampana', to: 'show#encampana'
  get '/legandodemexico', to: 'show#legandodemexico'
  get '/rueda', to: 'show#rueda'
  get '/santamarta', to: 'show#santamarta'
  get '/santander', to: 'show#santander'
  get '/velorio', to: 'show#velorio'

  get '/sinhorizonte', to: 'show#sinhorizonte'

  get '/ancianato', to: 'show#ancianato'
  get '/anoranza', to: 'show#anoranza'
  get '/armenia', to: 'show#armenia'
  get '/costumbre', to: 'show#costumbre'
  get '/dayofthedead1', to: 'show#dayofthedead1'
  get '/dayofthedead4', to: 'show#dayofthedead4'
  get '/drugtraffickingwar', to: 'show#drugtraffickingwar'
  get '/harvester', to: 'show#harvester'
  get '/ipiales', to: 'show#ipiales'
  get '/khidki', to: 'show#khidki'
  get '/killingtime', to: 'show#killingtime'
  get '/losteros', to: 'show#losteros'
  get '/maeugeniadavila', to: 'show#maeugeniadavila'
  get '/monterey', to: 'show#monterey'
  get '/mujercantinaleche', to: 'show#mujercantinaleche'
  get '/plazadebolivar', to: 'show#plazadebolivar'
  get '/plazadelmercado', to: 'show#plazadelmercado'
  get '/primeracomunion', to: 'show#primeracomunion'

  get '/jacarandoso', to: 'show#jacarandoso'
  get '/leticia', to: 'show#leticia'
  get '/madrid1986', to: 'show#madrid1986'
  get '/mariapazgaviria', to: 'show#mariapazgaviria'
  get '/ninobus', to: 'show#ninobus'
  get '/anarquia', to: 'show#anarquia'
  get '/presidentebarco', to: 'show#presidentebarco'
  get '/asombro', to: 'show#asombro'
  get '/childrenworking1', to: 'show#childrenworking1'
  get '/childrenworking2', to: 'show#childrenworking2'
  get '/childrenworking5', to: 'show#childrenworking5'
  get '/childrenworking', to: 'show#childrenworking'
  get '/girls2', to: 'show#girls2'
  get '/halloweensoldier', to: 'show#halloweensoldier'
  get '/children53', to: 'show#children53'
  get '/semana', to: 'show#semana'
  get '/slide5', to: 'show#slide5'
  get '/primeracomunion', to: 'show#primeracomunion'
  get '/touring', to: 'show#touring'


end
